// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://feydlvcgmwzlwuwhucbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZleWRsdmNnbXd6bHd1d2h1Y2J6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3Mjc2MTMsImV4cCI6MjA2MzMwMzYxM30.bwBCciEE7YeT2Cv9VDc3mp2mpsb9yIpSCABFC2Do1NY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);